    version: 2.1
    jobs:
    
#Job1
      Version_Check:
        docker:
          - image: cimg/python:3.11.3
        steps:
          - checkout
          - run: 
                name: python version
                command: |
                        python --version
                        docker --version
                        systemctl status docker
          
          
          




           

                    
        

#Workflows     
    workflows:
      Test-Deploy:
        jobs:
            - Version_Check
          
            
          
       
