    version: 2.1
    jobs:
    
#Job1
      Version_Check:
        docker:
          - image: cimg/python:3.11.3
        steps:
          - checkout
          - run: python --version
          
          
          
#Job2          
      InstallDjangoVersion:
        docker:
         - image: cimg/python:3.11.3
        steps:
            - checkout
            - run:
                command: |
                    pip install django
            

#Job3
      Migrations:
        docker:
         - image: cimg/python:3.11.3
        steps:
            - checkout
            - run:
                command: |
                    pip install django
                    python3 manage.py makemigrations

#Workflows     
    workflows:
      Test-Deploy:
        jobs:
        - Version_Check
        - InstallDjangoVersion:
            requires:
                - Version_Check
        - Migrations:
            requires:
                - InstallDjangoVersion
       
