    version: 2.1
    jobs:
    
#Job1
      Version_Check:
        docker:
          - image: cimg/python:3.11.3
        steps:
          - checkout
          - run: python --version
          
          
          
#Job2          
      Installing Django Version:
        docker:
         - image: cimg/python:3.11.3
        steps:
            - checkout
            - run:
                command: |
                    pip install django
            

#Job3
      Making Migrations:
        docker:
         - image: cimg/python:3.11.3
        steps:
            - checkout
            - run:
                command: |
                    pip install django
                    python3 manage.py makemigrations
                    
                    
              
#Job4
     Migrate file:
        docker:
         - image: cimg/python:3.11.3
        steps:
            - checkout
            - run:
                command: |
                    python3 manage.py migrate

#Workflows     
    workflows:
      Test-Deploy:
        jobs:
        - Version_Check
        - Installing Django Version:
            requires:
                - Version_Check
        - Making Migrations:
            requires:
                - InstallDjangoVersion
        - Migrate file:
            requires:
                - Making Migrations
       
