
    version: 2.1
    jobs:
        Version:
            docker:
                - image: madhupdevops/python-django-app-image:latest
            steps:
                - checkout
                - run:
                     name: docker
                     command: docker run -d -p 8000:8000 madhupdevops/python-django-app-image:latest
                       
              
    workflows:
            Test:
                jobs:
                    - Version
