    version: 2.1
    jobs:
    
#Job1
      Version_Check:
        docker:
          - image: cimg/python:3.11.3
        steps:
          - checkout
          - run: python --version
          
          
          
#Job2 
      Checking_Docker:
        docker:
           - image: cimg/python:3.11.3
        steps:
           - checkout
           - run: docker --version

                    
        

#Workflows     
    workflows:
      Test-Deploy:
        jobs:
            - Version_Check
            - Checking_Docker
            
          
       
