
    version: 2.1
    jobs:
        Version:
            docker:
                - image: cimg/python:3.11.3
            steps:
                - checkout
                - setup_remote_docker:
                     docker_layer_caching: true
                - run:
                     name: docker
                     command: docker build .
                       
              
    workflows:
            Test:
                jobs:
                    - Version
