
    version: 2.1
    jobs:
        Version:
            docker:
                - image: madhupdevops/python-django-app-image:latest
            steps:
                - checkout
                - run: echo "hello"
                       
              
    workflows:
            Test:
                jobs:
                    - Version
