    version: 2.1
    jobs:
    
#Job1
      Version_Check:
        docker:
          - image: cimg/python:3.11.3
        steps:
          - checkout
          - run: python --version
          
          
          
#Job2 
      Checking_Docker:
        docker:
           - image: cimg/python:3.11.3
        steps:
           - checkout
           - run: docker --version
           


#Job3 
      Pulling_Docker_Hello_World:
        docker:
           - image: cimg/python:3.11.3
        steps:
           - checkout
           - run: docker --version
           - run: 
             command: docker pull hello-world
           

                    
        

#Workflows     
    workflows:
      Test-Deploy:
        jobs:
            - Version_Check
            - Checking_Docker
            - Pulling_Docker_Hello_World:
                requires:
                    - Checking_Docker
            
          
       
