
    version: 2.1
    jobs:
        Version:
            docker:
                - image: madhupdevops/python-django-app-image:latest
            steps:
                - checkout
                - run: yum install docker -y
                       
              
    workflows:
            Test:
                jobs:
                    - Version
