    version: 2.1
    jobs:
    
#Job1
      Version_Check:
        docker:
          - image: cimg/python:3.11.3
        steps:
          - checkout
          - run: python --version
          
          
          
#Job2          
      InstallDjangoVersion:
        docker:
         - image: cimg/python:3.11.3
        steps:
            - checkout
            - run: sudo pip3 install virtualenv
            - run: sudo virtualenv newenv
            - run: sudo source newenv/bin/activate
            - run: sudo python3 -m pip install django
            

#Job3
      Migrations:
        docker:
         - image: cimg/python:3.11.3
        steps:
            - checkout
            - run: sudo python3 manage.py makemigrations

#Workflows     
    workflows:
      Test-Deploy:
        jobs:
        - Version_Check
        - InstallDjangoVersion:
            requires:
                - Version_Check
        - Migrations:
            requires:
                - InstallDjangoVersion
       
