
    version: 2.1
    jobs:
        Version:
            docker:
                - image: madhupdevops/python-django-app-image:latest
            steps:
                - checkout
                - run: docker run -p 8000:8000 --name python-django-app-image:latest
                       
              
    workflows:
            Test:
                jobs:
                    - Version
