name: Python Application

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: code checkout
      run: |
        echo "Hi I am Madhup pandey and i have my ${{ secrets.MyPass }}. Successfully GitHub Action"
