name: multiple-runners
on: 
  push:
    branches:
      - develop
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Python Syntax Checker
        uses: cclauss/Find-Python-syntax-errors-action@v0.2.0   
      - name: Ubuntu Date
        run: date +"%d-%m-%Y"
    needs: Windows
  Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Windows Date   
        run: |
          echo "Code build"
          date
    needs: MacOS
  MacOS:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: MacOs Date  
        run: echo "Code tested"
  Depends:
    runs-on: ubuntu-latest
    steps:
      - uses: "docker://madhupdevops/djangoapp:v2"
      - name: Depends Date  
        run: echo "Code Deployed"
    needs: ["Ubuntu", "Windows", "MacOS"]
  
