name: Python Application

on:
  push:
    branches: [ develop ]

jobs:
  Code-Checkout:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: code checkout
      run: |
        echo "Code checkout successfully"
  Build-Code:
    runs-on: ubuntu-latest
    needs: Code-Checkout
    steps:
      - uses: actions/checkout@v2
      - name: Code build
        run: |
          docker build -t myimage .
          echo "Code built successfully"  
          docker tag myimage madhupdevops/djangoapp:v1
          echo "${{ secret.dockerpass }}" | docker login -u "${{ secret.dockeruser }}" --password-stdin
          docker push madhupdevops/djangoapp:v1
